language = "auto"
unit_system = "SIBar"
window_alpha = 1.0

[default_units]
temperature = "Celsius"
temperature_diff = "Kelvin"
pressure = "Bar"
length = "Meter"
area = "SquareMeter"
volume = "CubicMeter"
velocity = "MeterPerSecond"
mass = "Kilogram"
viscosity = "PascalSecond"
energy = "Joule"
heat_transfer = "WPerSquareMeterK"
conductivity = "WPerMeterK"
specific_enthalpy = "KjPerKg"
